# Generated by Django 4.1.3 on 2023-01-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmetrics',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
