# Generated by Django 4.1.3 on 2023-01-13 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_site', '0002_businessmetrics_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('mains_gas', models.FloatField(default=0.0)),
                ('fuel', models.FloatField(default=0.0)),
                ('oil', models.FloatField(default=0.0)),
                ('coal', models.FloatField(default=0.0)),
                ('wood', models.FloatField(default=0.0)),
                ('grid_electricity', models.FloatField(default=0.0)),
                ('grid_electricity_LOWCARBON', models.FloatField(default=0.0)),
                ('waste_food_landfill', models.FloatField(default=0.0)),
                ('waste_food_compost', models.FloatField(default=0.0)),
                ('waste_food_charity', models.FloatField(default=0.0)),
                ('bottles_recycle', models.FloatField(default=0.0)),
                ('aluminum_can_recycle', models.FloatField(default=0.0)),
                ('general_waste_landfill', models.FloatField(default=0.0)),
                ('general_waste_recycle', models.FloatField(default=0.0)),
                ('special_waste', models.FloatField(default=0.0)),
                ('goods_delivered_company_owned', models.FloatField(default=0.0)),
                ('goods_delivered_contracted', models.FloatField(default=0.0)),
                ('travel_company_business', models.FloatField(default=0.0)),
                ('flights_domestic', models.FloatField(default=0.0)),
                ('flights_international', models.FloatField(default=0.0)),
                ('staff_commuting', models.FloatField(default=0.0)),
                ('beef_lamb', models.FloatField(default=0.0)),
                ('other_meat', models.FloatField(default=0.0)),
                ('lobster_prawn', models.FloatField(default=0.0)),
                ('fin_fish_seafood', models.FloatField(default=0.0)),
                ('milk_yoghurt', models.FloatField(default=0.0)),
                ('cheeses', models.FloatField(default=0.0)),
                ('fruit_veg_local', models.FloatField(default=0.0)),
                ('fruit_veg_other', models.FloatField(default=0.0)),
                ('dried_food', models.FloatField(default=0.0)),
                ('beer_kegs', models.FloatField(default=0.0)),
                ('beer_cans', models.FloatField(default=0.0)),
                ('beer_bottles', models.FloatField(default=0.0)),
                ('beer_kegs_LOWCARBON', models.FloatField(default=0.0)),
                ('beer_cans_LOWCARBON', models.FloatField(default=0.0)),
                ('beer_bottles_LOWCARBON', models.FloatField(default=0.0)),
                ('soft_drinks', models.FloatField(default=0.0)),
                ('wine', models.FloatField(default=0.0)),
                ('spirits', models.FloatField(default=0.0)),
                ('kitchen_equipment_asssets', models.FloatField(default=0.0)),
                ('building_repair_maintenance', models.FloatField(default=0.0)),
                ('cleaning', models.FloatField(default=0.0)),
                ('IT_Marketing', models.FloatField(default=0.0)),
                ('main_water', models.FloatField(default=0.0)),
                ('sewage', models.FloatField(default=0.0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator_site.business')),
            ],
        ),
    ]
