# Generated by Django 4.1.3 on 2023-01-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_site', '0003_carbonfootprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='businessmetrics',
            options={'verbose_name': 'Business Metric', 'verbose_name_plural': 'Business Metrics'},
        ),
        migrations.AlterModelOptions(
            name='businessusage',
            options={'verbose_name': 'Business Usage', 'verbose_name_plural': 'Business Usages'},
        ),
        migrations.AlterModelOptions(
            name='carbonfootprint',
            options={'verbose_name': 'Carbon Footprint', 'verbose_name_plural': 'Carbon Footprints'},
        ),
        migrations.AlterModelOptions(
            name='conversionfactor',
            options={'verbose_name': 'Convertion Factor', 'verbose_name_plural': 'Convertion Factors'},
        ),
    ]
