# Generated by Django 4.1.3 on 2023-01-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_site', '0004_alter_business_options_alter_businessmetrics_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessUsage',
        ),
        migrations.DeleteModel(
            name='ConversionFactor',
        ),
    ]
