# Generated by Django 4.1.3 on 2023-02-01 15:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_site', '0006_rename_kitchen_equipment_asssets_carbonfootprint_kitchen_equipment_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('E', 'Energy'), ('F', 'Food'), ('B', 'Beer'), ('W', 'Waste'), ('T', 'Travel'), ('O', 'Operations'), ('M', 'Miscellaneous')], max_length=1)),
                ('text', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Pledge',
                'verbose_name_plural': 'Pledges',
            },
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='IT_Marketing',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='aluminum_can_recycle',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='beef_lamb',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='beer_bottles',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='beer_bottles_LOWCARBON',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='beer_cans',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='beer_cans_LOWCARBON',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='beer_kegs',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='beer_kegs_LOWCARBON',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='bottles_recycle',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='building_repair_maintenance',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='cheeses',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='cleaning',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='coal',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='dried_food',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='fin_fish_seafood',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='flights_domestic',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='flights_international',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='fruit_veg_local',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='fruit_veg_other',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='fuel',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='general_waste_landfill',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='general_waste_recycle',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='goods_delivered_company_owned',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='goods_delivered_contracted',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='grid_electricity',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='grid_electricity_LOWCARBON',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='kitchen_equipment_assets',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='lobster_prawn',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='main_water',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='mains_gas',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='milk_yoghurt',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='oil',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='other_meat',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='sewage',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='soft_drinks',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='special_waste',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='spirits',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='staff_commuting',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='travel_company_business',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='waste_food_charity',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='waste_food_compost',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='waste_food_landfill',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='wine',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='carbonfootprint',
            name='wood',
            field=models.FloatField(default=-1),
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('reduce_electricity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('switch_electricity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reduce_gas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reduce_oil', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reduce_coal', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reduce_wood', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('energy_audit', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('swap_beef_lamb_for_non_meat', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('swap_beef_lamb_for_other_meat', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('swap_other_meat_for_non_meat', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('replace_fruit_veg', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('detailed_menu', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reduce_food_waste', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('waste_audit', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('switch_hc_beer_for_lc_beer', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('switch_bottle_beer_for_kegs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('switch_bottle_beer_for_cans', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reduce_general_waste', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reduce_vehicle_travel_miles', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reduce_commuting_miles', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reduce_staff_flights', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reduce_emissions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('adopt_sustainable_diposable_items', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sustainable_procuremed_equipment', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator_site.business')),
            ],
            options={
                'verbose_name': 'Action Plan',
                'verbose_name_plural': 'Action Plans',
                'unique_together': {('business', 'year')},
            },
        ),
    ]
