# Generated by Django 4.1.3 on 2023-01-26 10:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_site', '0006_rename_kitchen_equipment_asssets_carbonfootprint_kitchen_equipment_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator_site.business')),
            ],
            options={
                'verbose_name': 'Action Plan',
                'verbose_name_plural': 'Action Plans',
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('E', 'Energy'), ('F', 'Food'), ('B', 'Beer'), ('W', 'Waste'), ('T', 'Travel'), ('O', 'Operations'), ('M', 'Miscellaneous')], max_length=1)),
                ('text', models.CharField(max_length=150)),
                ('boolean', models.BooleanField()),
                ('fields', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Pledge',
                'verbose_name_plural': 'Pledges',
            },
        ),
        migrations.CreateModel(
            name='SelectedPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator_site.actionplan')),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator_site.pledge')),
            ],
            options={
                'verbose_name': 'Selected Pledge',
                'verbose_name_plural': 'Selected Pledges',
            },
        ),
        migrations.AddField(
            model_name='actionplan',
            name='selected_pledges',
            field=models.ManyToManyField(blank=True, to='calculator_site.selectedpledge'),
        ),
        migrations.AlterUniqueTogether(
            name='actionplan',
            unique_together={('business', 'year')},
        ),
    ]
