# Generated by Django 4.1.3 on 2023-01-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_site', '0007_actionplan_pledge_selectedpledge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='fields',
            new_name='formula',
        ),
    ]
