# Generated by Django 4.1.3 on 2023-02-02 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_site', '0007_pledge_alter_carbonfootprint_it_marketing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='switch_canned_beer_for_kegs',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
