# Generated by Django 4.1.3 on 2023-02-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator_site", "0008_actionplan_switch_canned_beer_for_kegs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actionplan",
            old_name="sustainable_procuremed_equipment",
            new_name="sustainably_procure_equipment",
        ),
    ]
