# Generated by Django 4.1.3 on 2023-02-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator_site",
            "0009_rename_sustainable_procuremed_equipment_actionplan_sustainably_procure_equipment",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="company_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
