# Generated by Django 4.1 on 2023-03-04 13:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "calculator_site",
            "0012_alter_actionplan_adopt_sustainable_diposable_items_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "had_enough_information",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_had_enough_information",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "scope_was_useful",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_scope_was_useful",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "able_to_find_info",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_able_to_find_info",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "calculator_ware_clear",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_calculator_ware_clear",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "question_were_relevant",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_question_were_relevant",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "graphics_ware_clear",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_graphics_ware_clear",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "pledge_were_relevant",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_pledge_were_relevant",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "cut_emissions",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                ("comment_cut_emissions", models.CharField(default="", max_length=150)),
                (
                    "action_plan_clear_use",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_action_plan_clear_use",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "aware_of_carbon_impacts",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_aware_of_carbon_impacts",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "confident_able_to_complete",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_confident_able_to_complete",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "know_climate_change",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_know_climate_change",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "actions_improve_business",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_actions_improve_business",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "customer_exercise",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_customer_exercise",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "all_stores_complete_exercise",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_all_stores_complete_exercise",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "climate_change_emergency",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_climate_change_emergency",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "want_to_find_out_climate_change",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_want_to_find_out_climate_change",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "opportunities_to_supplier",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_opportunities_to_supplier",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "calculator_too_hard",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "comment_calculator_too_hard",
                    models.CharField(default="", max_length=150),
                ),
                (
                    "happy_to_talk",
                    models.IntegerField(
                        choices=[
                            (0, "Strongly Agree"),
                            (10, "Agree"),
                            (20, "Unsure"),
                            (30, "Disagree"),
                            (40, "Strongly Disagree"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                ("comment_happy_to_talk", models.CharField(default="", max_length=150)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedback",
            },
        ),
        migrations.CreateModel(
            name="ActionPlanDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("ownership", models.CharField(default="", max_length=200)),
                (
                    "start_date",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "end_date",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("text", models.CharField(default="", max_length=200)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator_site.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action Plan Detail",
                "verbose_name_plural": "Action Plan Details",
            },
        ),
    ]
