# Generated by Django 4.1 on 2023-03-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator_site", "0013_feedback_actionplandetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionplandetail",
            name="plan_detail",
            field=models.CharField(default="", max_length=200),
        ),
    ]
