# Generated by Django 4.1 on 2023-03-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator_site", "0014_actionplandetail_plan_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionplandetail",
            name="end_date",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="actionplandetail",
            name="start_date",
            field=models.CharField(default="", max_length=200),
        ),
    ]
