# Generated by Django 4.1 on 2023-03-17 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator_site", "0016_alter_actionplandetail_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionplandetail",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 17, 16, 5, 14, 380191, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="actionplandetail",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 17, 16, 5, 14, 380191, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
